

.\" Manpage for Nere
.\" Contact ninja.aung02@gmail.com to correct errors or typos.
.TH man 1 "09 jan 2019" "1.0" "Nere"
.SH NAME
nere \- create, update and delete repositories
.SH SYNOPSIS
.B nere 
[\fBhelp\fR]
[\fB\-u\fR \fIUSERNAME\fR]
[\fB\-c\fR \fIREPONAME\fR]
[\fB\-\-desc\fR \TEXT\fR]
[\fB\-p\fR]
[\fB\-a\fR \fITOKEN\fR]
.SH DESCRIPTION
nere allows users to create, delete and update repositories straight from the terminal
.SH OPTIONS
A list of options as follows:
.TP
.BR \-h ", " \-\-help\fR
Displays the options for nere

.TP
.BR \-u ", " \-\-username=\fIUSERNAME\fR
passes a temporary username to the command

.TP
.BR \-c ", " \-\-create =\fIREPONAME\fR
passes the name of the reposiotry

.TP
.BR \-\-desc=\fITEXT\fR
provide a decription to the repository

.TP
.BR \-d ", " \-\-delete=\fIUSERNAME\fR
passes a temporary username to the command

.TP
.BR \-a ", " \-\-auth=\fITOKEN\fR
passes token or password for anything requiring authorization

.TP
.BR \-u ", " \-\-username=\fIUSERNAME\fR
passes a temporary username to the command

.TP
.BR \-p ", " \-\-private\fR
Flag signifies the repository is private
.SH BUGS
No known bugs.
.SH AUTHORs
Nyein Chan Aung (Ninja.aung02@gmail.com)